|^|Welcome|^|This is our general discussion forum. If you feel like chatting with other members you can do it here.|^|On|^|is not|^|is|^|allreg&allreg|^||^|1|^||^|ON|^|no|^||^||^|000001|^|date|^|This is our general discussion forum. If you feel like chatting with other members you can do it here.|^|1|^|
|^|Post-a-Ride|^|Going for a ride? Want to invite folks to join you? Post it here. |^|On|^|is not|^|is|^|allreg&allreg|^||^|2|^||^|ON|^|no|^||^||^|000002|^|date|^|Want to organize a ride but miss the deadline for the newsletter? Just want to let folks you're going for a ride and they're welcome to come along? Here's your place.|^|1|^|
|^|Racing|^|An open forum to discuss racing. |^|On|^|is not|^|is|^|allreg&allreg|^||^|3|^||^|ON|^|no|^||^||^|000004|^|date|^|Want to discuss local racing? Need a ride to the race in Portland next week or just want to chat about the Classics? This is your spot.|^|1|^|
|^|Wrench & Gear|^|Seeking advice on a repair or just need some sage advice on a purchase? Come on in.|^|On|^|is not|^|is|^|allreg&allreg|^||^|4|^||^|ON|^|no|^||^||^|000006|^|date|^| <body bgcolor="#ffffff"> <p><font size="2" face="Arial,Helvetica,Geneva,Swiss,SunSans-Regular">Seeking advice on a repair or just need some sage advice on a purchase? You're in the right place.</font></p> </body> </html>|^|1|^|
|^|Rides|^|Looking for information about a ride or just a question about a specific route? Answers are here.|^|On|^|is not|^|is|^|allreg&allreg|^||^|5|^||^|ON|^|no|^||^||^|000005|^|date|^|Have an idea for a ride, need help planning a vacation around rides? Ask away.|^||^|
|^|Mountain Lakes Challenge|^|We'll post official information for the Mountain Lakes Challenge here. If you have any questions, try them on us.|^|On|^|is not|^|is|^|allreg&allreg|^||^|6|^||^|ON|^|no|^||^||^|000003|^|date|^|The Mountain Lakes Challenge is the the major yearly event for the Siskiyou Velo. |^||^|
|^|Women's Rides & Riders|^|An open forum to discuss Women's cycling - post rides or whatever seems appropriate.|^|On|^|is not|^|is|^|allreg&allreg|^||^|7|^||^|ON|^|no|^||^||^|000007|^|date|^||^||^|
|^|For Sale & Exchange|^|Need to post something for sale and post it quickly? |^|On|^|is not|^|is|^|allreg&allreg|^||^|8|^||^|ON|^|no|^||^||^|000008|^|date|^|This is an open forum - Please remember to leave contact information and reply when the item has been sold.|^||^|
|^||^|Forum 9 Description|^|Off|^|is not|^|is|^|allreg&allreg|^||^|9|^||^|ON|^|no|^||^|yes|^|000000|^|date|^||^||^|
|^||^||^|Off|^|is not|^|is|^|allreg&allreg|^||^|10|^||^|ON|^|no|^||^||^|000000|^|date|^||^||^|
