<h1>Bicycle Advocates Wanted!</h1>
<p>It doesn't take much to become an advocate for bicycle safety and help improve the overall riding conditions in the Rogue Valley.</p>

<p>What's an advocate? Webster's Unabridged Dictionary describes and advocate as one who defends, vindicates, or espouses a cause by argument; one who is friendly to; an upholder, a defender. An advocacy is the act of pleading for or supporting.</p>

<p>The Rogue Valley needs advocates for better bicycle transportation planning and a friendlier bicycle riding atmosphere. We all need to be advocates to affect change. Those that are in a position to affect change need to know that there are a lot of us in the community who ride bicycles. And, they need to know that we are concerned enough to voice our opinions and needs.</p>

<p>How can we be more proactive advocates for bicycling? For starters, take a look at our <a href="advocacy.php?pageID=Contacts">resources and contact information</a> as well as the other pages within this section. Additionally, <a href="http://www.mailtribune.com">The Medford Mail Tribune</a> has run numerous stories in the last few months on bicycle riding in the valley. How about a letter or phone call to them with a pat on the back for supporting the cycling community? Or better yet, how about suggesting a story about bicycling activities? Edgar Hee has written some excellent editorials supporting the bicycling community. How about a more letters to the editor from club members? More letters with a positive or proactive theme about bicycling could expand people's knowledge of what it's like to cycle in a town rated a D-minus. Attending public meetings on city or county transportation planning keeps cycling concerns in the forefront. Alerting the city or county of dangerous riding conditions may get some action. Alerting the local police, sheriffs, or highway patrol of dangerous actions or situations can help reduce those instances.</p>

<p>You probably can think of other ways to be an advocate. As members of the Siskiyou Velo bicycle club, our 300+ members can be a nucleus of strong catalyst for change. Each of us can make a difference by taking just a few minutes to advocate the need for a safer, friendlier place to experience our passion of riding bicycles. Based on my career working with public issues and my life experiences, the silent majority rarely gets change. The vocal minority often gets action much quicker. If we bicyclists are going to see positive changes in the Rogue Valley, we need to form a stronger advocacy for a better bicycle community and we need to be stronger advocates for our safety and transportation needs as bicyclists. I hope you can find the time to help make a difference for the bicycle community. And, don't forget to enjoy some great rides in the Rogue Valley! Just having more bicyclists on the streets on a regular basis will help people notice that there are lots of us. Remember... be a courteous rider. You represent a lot of us by your actions as a rider.</p>